"""added task table

Revision ID: 327294d6c621
Revises: 8977cef25632
Create Date: 2025-07-17 03:25:53.076865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '327294d6c621'
down_revision = '8977cef25632'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Enum('todo', 'in_progress', 'completed', name='taskstatusenum'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
