"""added task table

Revision ID: 763a918471eb
Revises: b3f59ff6c379
Create Date: 2025-07-17 03:00:55.487874

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '763a918471eb'
down_revision = 'b3f59ff6c379'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('task_code'))
        batch_op.drop_column('task_code')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('task_code', mysql.VARCHAR(length=100), nullable=False))
        batch_op.create_index(batch_op.f('task_code'), ['task_code'], unique=True)

    # ### end Alembic commands ###
