"""added task table

Revision ID: 8977cef25632
Revises: 763a918471eb
Create Date: 2025-07-17 03:25:28.661440

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8977cef25632'
down_revision = '763a918471eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', mysql.ENUM('backlog', 'todo', 'in_progress', 'in_review', 'done'), nullable=False))

    # ### end Alembic commands ###
