"""added tables

Revision ID: eb0b770563cb
Revises: 474fe578bb13
Create Date: 2025-07-16 23:14:18.897851

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb0b770563cb'
down_revision = '474fe578bb13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('upwork_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('skills', sa.JSON(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('client_country', sa.String(length=100), nullable=True),
    sa.Column('client_payment_verified', sa.Boolean(), nullable=True),
    sa.Column('client_total_spent', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('client_jobs_posted', sa.Integer(), nullable=True),
    sa.Column('client_hire_rate', sa.String(length=10), nullable=True),
    sa.Column('client_reviews', sa.Text(), nullable=True),
    sa.Column('budget', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('budget_type', sa.Enum('fixed', 'hourly', name='budgettypeenum'), nullable=True),
    sa.Column('project_length', sa.String(length=100), nullable=True),
    sa.Column('hours_per_week', sa.String(length=50), nullable=True),
    sa.Column('proposals_submitted', sa.Integer(), nullable=True),
    sa.Column('interviewing', sa.Integer(), nullable=True),
    sa.Column('invites_sent', sa.Integer(), nullable=True),
    sa.Column('connect_required', sa.Integer(), nullable=True),
    sa.Column('expected_cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('expected_earnings', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('posted_at', sa.DateTime(), nullable=True),
    sa.Column('job_url', sa.Text(), nullable=False),
    sa.Column('feasibility_status', sa.Enum('pending', 'valid', 'scam', 'unsure', name='feasibilityenum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id')
    )
    op.create_table('proposals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('generated_by', sa.Integer(), nullable=False),
    sa.Column('cover_letter', sa.Text(), nullable=True),
    sa.Column('proposal', sa.Text(), nullable=False),
    sa.Column('feasibility_score', sa.Float(), nullable=True),
    sa.Column('feasibility_reason', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'sent', 'rejected', 'accepted', name='proposalstatusenum'), nullable=False),
    sa.Column('connects_required', sa.Integer(), nullable=True),
    sa.Column('expected_cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('expected_earnings', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('job_description', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('project_duration', sa.String(length=100), nullable=True),
    sa.Column('overall_score', sa.Float(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['generated_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['upwork_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('team_lead_id', sa.Integer(), nullable=False),
    sa.Column('proposal_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('active', 'completed', name='projectstatusenum'), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['upwork_jobs.id'], ),
    sa.ForeignKeyConstraint(['proposal_id'], ['proposals.id'], ),
    sa.ForeignKeyConstraint(['team_lead_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_members',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('role_in_project', sa.String(length=100), nullable=True),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'project_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project_members')
    op.drop_table('projects')
    op.drop_table('proposals')
    op.drop_table('upwork_jobs')
    # ### end Alembic commands ###
